<div class="space-y-6" wire:poll.15s>
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div><p class="text-sm text-zinc-500">Workspace</p><h1 class="text-3xl font-semibold">Falqo</h1></div>
        @if($activeTimer)<flux:button wire:click="stopTimer" variant="danger">Stop · {{ $activeTimer->project->name }}</flux:button>@endif
    </div>
    @if($errors->any())<flux:callout variant="danger">{{ $errors->first() }}</flux:callout>@endif

    @if($section === 'overview')
        <div class="grid gap-4 md:grid-cols-4">@foreach([['Customers',$customers->count()],['Active projects',$projects->where('status','active')->count()],['Open tickets',$tickets->where('status','open')->count()],['Tracked today',intdiv($minutesToday,60).'h '.($minutesToday%60).'m']] as [$label,$value])<div class="rounded-xl border border-zinc-200 p-5 dark:border-zinc-700"><p class="text-sm text-zinc-500">{{ $label }}</p><p class="mt-2 text-3xl font-semibold">{{ $value }}</p></div>@endforeach</div>
        <div class="grid gap-5 lg:grid-cols-2"><div class="rounded-xl border border-zinc-200 p-5 dark:border-zinc-700"><h2 class="font-semibold">Start tracking</h2><form wire:submit="startTimer" class="mt-4 space-y-3"><flux:select wire:model.live="projectId" placeholder="Choose project">@foreach($projects as $project)<flux:select.option value="{{ $project->id }}">{{ $project->name }}</flux:select.option>@endforeach</flux:select><flux:select wire:model="taskId" placeholder="No specific task">@foreach($tasks->where('project_id',$projectId) as $task)<flux:select.option value="{{ $task->id }}">{{ $task->title }}</flux:select.option>@endforeach</flux:select><flux:input wire:model="description" placeholder="What are you working on?"/><flux:button type="submit" variant="primary">Start timer</flux:button></form></div><div class="rounded-xl border border-zinc-200 p-5 dark:border-zinc-700"><h2 class="font-semibold">Recent time</h2>@forelse($entries->take(5) as $entry)<div class="flex justify-between border-b border-zinc-200 py-3 last:border-0 dark:border-zinc-700"><span>{{ $entry->project->name }}</span><code>{{ intdiv($entry->minutes,60) }}:{{ str_pad($entry->minutes%60,2,'0',STR_PAD_LEFT) }}</code></div>@empty<p class="mt-4 text-sm text-zinc-500">No time logged yet.</p>@endforelse</div></div>
    @elseif($section === 'customers')
        <div><h2 class="text-2xl font-semibold">Customers</h2><form wire:submit="addCustomer" class="my-5 grid gap-3 md:grid-cols-3"><flux:input wire:model="name" placeholder="Customer name"/><flux:input wire:model="email" type="email" placeholder="Email"/><flux:button type="submit" variant="primary">Add customer</flux:button></form>@forelse($customers as $customer)<div class="item"><span>{{ $customer->name }} <small>{{ $customer->email }}</small></span><flux:badge>{{ $customer->projects_count }} projects</flux:badge></div>@empty<p class="empty">Add your first customer.</p>@endforelse</div>
    @elseif($section === 'projects')
        <div><h2 class="text-2xl font-semibold">Projects</h2><form wire:submit="addProject" class="my-5 grid gap-3 md:grid-cols-4"><flux:input wire:model="name" placeholder="Project name"/><flux:select wire:model="customerId" placeholder="Customer">@foreach($customers as $customer)<flux:select.option value="{{ $customer->id }}">{{ $customer->name }}</flux:select.option>@endforeach</flux:select><flux:input wire:model="description" placeholder="Description"/><flux:button type="submit" variant="primary">Add project</flux:button></form>@forelse($projects as $project)<div class="item"><span>{{ $project->name }} <small>{{ $project->customer->name }}</small></span><flux:badge>{{ $project->status }}</flux:badge></div>@empty<p class="empty">Create a customer first.</p>@endforelse</div>
    @elseif($section === 'tickets')
        <div><h2 class="text-2xl font-semibold">Tickets</h2><form wire:submit="addTicket" class="my-5 grid gap-3 md:grid-cols-5"><flux:input wire:model="title" placeholder="Ticket subject"/><flux:select wire:model="customerId" placeholder="Customer">@foreach($customers as $customer)<flux:select.option value="{{ $customer->id }}">{{ $customer->name }}</flux:select.option>@endforeach</flux:select><flux:select wire:model="projectId" placeholder="Optional project">@foreach($projects as $project)<flux:select.option value="{{ $project->id }}">{{ $project->name }}</flux:select.option>@endforeach</flux:select><flux:select wire:model="priority"><flux:select.option>normal</flux:select.option><flux:select.option>high</flux:select.option><flux:select.option>urgent</flux:select.option></flux:select><flux:button type="submit" variant="primary">Add ticket</flux:button></form>@forelse($tickets as $ticket)<div class="item"><span>#{{ $ticket->id }} · {{ $ticket->title }} <small>{{ $ticket->customer->name }}</small></span><flux:badge>{{ $ticket->priority }}</flux:badge></div>@empty<p class="empty">No tickets yet.</p>@endforelse</div>
    @elseif($section === 'tasks')
        <div><h2 class="text-2xl font-semibold">Tasks</h2><form wire:submit="addTask" class="my-5 grid gap-3 md:grid-cols-3"><flux:input wire:model="title" placeholder="Task title"/><flux:select wire:model="projectId" placeholder="Project">@foreach($projects as $project)<flux:select.option value="{{ $project->id }}">{{ $project->name }}</flux:select.option>@endforeach</flux:select><flux:button type="submit" variant="primary">Add task</flux:button></form>@forelse($tasks as $task)<button wire:click="toggleTask({{ $task->id }})" class="item w-full text-left"><span @class(['line-through opacity-50'=>$task->status==='done'])>{{ $task->title }} <small>{{ $task->project->name }}</small></span><flux:badge>{{ $task->status }}</flux:badge></button>@empty<p class="empty">No tasks yet.</p>@endforelse</div>
    @else
        <div><h2 class="text-2xl font-semibold">Time entries</h2>@forelse($entries as $entry)<div class="item"><span>{{ $entry->project->name }} <small>{{ $entry->started_at->format('M j, H:i') }} · {{ $entry->description }}</small></span><code>{{ intdiv($entry->minutes,60) }}h {{ $entry->minutes%60 }}m</code></div>@empty<p class="empty">No time entries yet.</p>@endforelse</div>
    @endif
</div>
